config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :members do
    resources :profiles
  end
  resources :profiles
  
  root 'home#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_one :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :member
	validates :bio, presence: true
	validates :member_id, presence: true

	has_attached_file :profile_pic,
	 styles: { small: "100x100#" },
	 default_url: "/images/:style/missing.png"
	validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  alias_method :current_user, :current_member

  # rescue_from Pundit::NotAuthorizedError, with: :member_not_authorized
   private
   def member_not_authorized
   flash[:alert] = "You are not authorized to perform this action."
   redirect_to(request.referrer || root_path)
   end

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_member
  # before_action :authenticate_member!
  before_action :authenticate_member!

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    authorize @profiles
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    
  end

  # GET /profiles/new
  def new
    @profile = @member.build_profile
    authorize @profile
  end

  # GET /profiles/1/edit
  def edit
    
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = @member.create_profile(profile_params)
    authorize @profile
    respond_to do |format|
      if @profile.save
        format.html { redirect_to member_profiles_path(@member, @profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
      authorize @profile
    end

    def set_member
      @member = Member.find(params[:member_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:bio, :member_id, :profile_pic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<p>Welcome to Better Than AirBnB</p>

<%= link_to "Become a host", new_member_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if member_signed_in? %>
 <%= render "shared/logged_in_header" %>
<% else %>
 <%= render "shared/logged_out_header" %>
<% end %>

<% unless notice.blank? %>
	<%= notice %>
<% end %>

<% unless alert.blank? %>
	<%= alert %>
<% end %>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for [@member, @profile], html: {multipart: true} do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.file_field :profile_pic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Bio</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.bio %></td>
        <td><%= profile.member_id %></td>
        <td><%= link_to 'Show', member_profile_path(@member, profile) %></td>
        <td><%= link_to 'Edit', edit_member_profile_path(@member, profile) %></td>
        <td><%= link_to 'Destroy', [@member, profile], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_member_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Member:</strong>
  <%= @profile.member_id %>
</p>

app/views/shared/_logged_in_header.html.erb
<%= link_to "Sign out", destroy_member_session_path, method: :delete  %>

app/views/shared/_logged_out_header.html.erb
<%= link_to "Log in", new_member_session_path  %>